name: tka_customer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  permission_handler: ^12.0.0+1
  font_awesome_flutter: ^10.8.0
  get_storage: ^2.1.1
  intl: ^0.20.2
  shimmer: ^3.0.0
  video_player: ^2.5.5
  google_maps_flutter: ^2.12.1
  flutter_polyline_points: ^2.1.0
  onesignal_flutter: ^5.3.0
  google_fonts: ^6.2.1
  flutter_image_compress: ^2.4.0
  video_compress: ^3.1.4
  chewie: ^1.11.3
  photo_view: ^0.15.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/app.png"

  flavors:
    rusco:
      image_path: "assets/icon/ruscon_icons.png"
    tka:
      image_path: "assets/icon/ottogo_icons.png"
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/car.png
    - assets/icon/driver.png
    - assets/icon/mark_mekanik.png
    - assets/icon/mark_mekanik1.png
    - assets/icon/mechanic.png
    - assets/icon/no_conexion.png
    - assets/icon/ottogo_icons.png
    - assets/icon/ruscon_icons.png
    - assets/logo/logo-ottogo.png
    - assets/logo/logo-rusco.png
    - assets/logo/logo_dev.png
