// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'tka_customer';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String CAR = 'assets/icon/car.png';
  static const String DRIVER = 'assets/icon/driver.png';
  static const String MARK_MEKANIK = 'assets/icon/mark_mekanik.png';
  static const String MARK_MEKANIK1 = 'assets/icon/mark_mekanik1.png';
  static const String MECHANIC = 'assets/icon/mechanic.png';
  static const String NO_CONEXION = 'assets/icon/no_conexion.png';
  static const String OTTOGO_ICONS = 'assets/icon/ottogo_icons.png';
  static const String RUSCON_ICONS = 'assets/icon/ruscon_icons.png';
  static const String SERVER_DOWN = 'assets/icon/server-down.png';
  static const String LOGO_OTTOGO = 'assets/logo/logo-ottogo.png';
  static const String LOGO_RUSCO = 'assets/logo/logo-rusco.png';
  static const String LOGO_DEV = 'assets/logo/logo_dev.png';
  static const String EMERGENCY1 = 'assets/penggunaan/emergency1.png';
  static const String EMERGENCY2 = 'assets/penggunaan/emergency2.png';
  static const String EMERGENCY3 = 'assets/penggunaan/emergency3.png';
  static const String EMERGENCY4 = 'assets/penggunaan/emergency4.png';
  static const String REQUEST1 = 'assets/penggunaan/request1.png';
  static const String REQUEST2 = 'assets/penggunaan/request2.png';
  static const String REQUEST3 = 'assets/penggunaan/request3.png';
  static const String REQUEST4 = 'assets/penggunaan/request4.png';
  static const String SERVICE = 'assets/penggunaan/service.png';
}
