// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'tka_customer';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String CAR = 'assets/icon/car.png';
  static const String DRIVER = 'assets/icon/driver.png';
  static const String MARK_MEKANIK = 'assets/icon/mark_mekanik.png';
  static const String MARK_MEKANIK1 = 'assets/icon/mark_mekanik1.png';
  static const String MECHANIC = 'assets/icon/mechanic.png';
  static const String NO_CONEXION = 'assets/icon/no_conexion.png';
  static const String OTTOGO_ICONS = 'assets/icon/ottogo_icons.png';
  static const String RUSCON_ICONS = 'assets/icon/ruscon_icons.png';
  static const String LOGO_RMBG = 'assets/logo/logo-rmbg.png';
  static const String LOGO_RMBG2 = 'assets/logo/logo-rmbg2.png';
}
